#
# evdi-kmod.spec -- kernel-module half of EVDI, packaged as an akmod.
#
# Companion to evdi.spec (which builds libevdi).  See evdi.spec for why the two
# are separate source packages.
#
# HOW THIS WORKS
# --------------
# There are two build modes, selected by whether %%{kernels} is defined:
#
#   1. %%{kernels} UNDEFINED -- the normal COPR/mock build.  kmodtool is invoked
#      with --akmod and emits only:
#          akmod-evdi   : ships this very SRPM under /usr/src/akmods/
#          kmod-evdi    : empty metapackage requiring akmod-evdi
#      NO kernel module is compiled here, so no kernel-devel is needed in the
#      buildroot.  This is what COPR publishes.
#
#   2. %%{kernels} DEFINED -- what /usr/sbin/akmods does on the user's machine
#      after a kernel update.  It runs akmodsbuild, which rebuilds this SRPM
#      with --define "kernels <kver>".  kmodtool then emits a real
#      kmod-evdi-<kver> subpackage and defines %%{kernel_versions},
#      %%{kmodinstdir_prefix} and %%{kmodinstdir_postfix}; the loops below
#      actually compile evdi.ko against that kernel.
#
# The Name MUST be "evdi-kmod": kmodtool derives %%{pkg_kmod_name} from it, and
# the akmod-evdi %%post hardcodes
#     /usr/sbin/akmods-ostree-post evdi %%{_usrsrc}/akmods/%%{pkg_kmod_name}-%%{version}-%%{release}.src.rpm
# i.e. it looks the SRPM up by that exact filename.  That is the code path used
# on rpm-ostree systems (Silverblue/Kinoite), so getting the name wrong breaks
# precisely the target platform.
#

# Build the akmod (source) package rather than per-kernel binary kmods.
%global buildforkernels akmod

# .ko debuginfo is handled by the kmod machinery, not the normal debug package.
%global debug_package %{nil}

Name:           evdi-kmod
Version:        1.15.0
Release:        1%{?dist}
Summary:        Kernel module (akmod) for EVDI (Extensible Virtual Display Interface)

# Everything shipped by this package comes from evdi/module/, whose sources all
# carry "SPDX-License-Identifier: GPL-2.0-only" and which ships module/LICENSE =
# GPL v2.  (module/evdi_drm.h, the uapi header, is
# "GPL-2.0 WITH Linux-syscall-note", which is the standard uapi exception and
# does not change the binary module's license.)  The userspace library is
# LGPL-2.1-or-later and lives in the separate evdi source package.
License:        GPL-2.0-only
URL:            https://github.com/DisplayLink/evdi
Source0:        %{url}/archive/refs/tags/v%{version}/evdi-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  make
BuildRequires:  elfutils-libelf-devel
BuildRequires:  kmodtool
BuildRequires:  redhat-rpm-config
# Defines %%{_modulesloaddir}.  Do NOT drop this: it gets pulled into a fat
# buildroot by accident (akmods -> systemd), so a local build can succeed while
# a minimal mock/COPR chroot fails with
#   error: File must begin with "/": %%{_modulesloaddir}/evdi.conf
BuildRequires:  systemd-rpm-macros

# The kernel is only built for these on Fedora; kmods elsewhere are pointless.
ExclusiveArch:  x86_64 aarch64

# kmodtool writes the akmod-evdi / kmod-evdi / kmod-evdi-<kver> subpackages,
# their scriptlets, and the %%{kernel_versions} + %%{kmodinstdir_*} macros used
# below.  With --akmod and no %%{kernels} it does NOT need kernel-devel, which
# is what makes this buildable in a plain COPR chroot.
%{expand:%(kmodtool --target %{_target_cpu} --kmodname %{name} %{?buildforkernels:--%{buildforkernels}} %{?kernels:--for-kernels "%{?kernels}"} 2>/dev/null)}

%description
EVDI (Extensible Virtual Display Interface) is a Linux kernel module that
creates virtual displays: DRM connectors the compositor treats as real
monitors, whose framebuffer is handed back to userspace instead of being
scanned out to physical hardware.

This source package builds the kernel module as an akmod, which is rebuilt
automatically against every newly installed kernel.  The userspace library is
provided by libevdi (source package evdi).

# akmod-evdi and kmod-evdi-<kver> both carry an unconditional
#     Requires: %%{pkg_kmod_name}-common >= %%{version}
# generated by kmodtool, so this subpackage is mandatory -- without it
# akmod-evdi is uninstallable.
#
# Only build it in the COPR pass.  During an akmodsbuild rebuild (%%{kernels}
# defined) it is already installed, and akmods blindly `dnf install`s every rpm
# the rebuild produced, so re-emitting it here would just create churn.
%if 0%{!?kernels:1}
%package -n %{pkg_kmod_name}-common
Summary:        Common files for the EVDI kernel module

%description -n %{pkg_kmod_name}-common
License, documentation and the modules-load.d snippet shared by every flavor
of the evdi kernel module.

%files -n %{pkg_kmod_name}-common
%license module/LICENSE
%doc module/README.md
%{_modulesloaddir}/evdi.conf
%endif

%prep
%autosetup -n evdi-%{version}

# One build tree per kernel.  Empty (no-op) in the COPR/akmod pass.
for kernel_version in %{?kernel_versions}; do
    cp -a module _kmod_build_${kernel_version%%___*}
done

%build
# Kernel modules must NOT inherit the userspace RPM optflags.  module/Makefile's
# in-kbuild branch does
#     ccflags-y := -isystem include/uapi/drm $(CFLAGS)
# so anything RPM leaves in $CFLAGS (-O2, hardening, -flto, ...) gets spliced
# straight into the kbuild compile line and breaks the module.  Scrub them.
# (Deliberately no %%set_build_flags here -- the opposite of evdi.spec.)
unset CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS

for kernel_version in %{?kernel_versions}; do
    make %{?_smp_mflags} -C "${kernel_version##*___}" \
        M="${PWD}/_kmod_build_${kernel_version%%___*}" modules
done

%install
for kernel_version in %{?kernel_versions}; do
    install -D -m 0755 \
        _kmod_build_${kernel_version%%___*}/evdi.ko \
        %{buildroot}%{kmodinstdir_prefix}/${kernel_version%%___*}/%{kmodinstdir_postfix}/evdi.ko
done
# kmodtool's %%__spec_install_post then signs (if a MOK keypair exists under
# /etc/pki/akmods) and xz-compresses the .ko for us.

%if 0%{!?kernels:1}
# Autoload evdi at boot.  The module defaults to initial_device_count=0, so
# loading it creates no displays and costs nothing -- but without it loaded
# /sys/devices/platform/evdi/add does not exist, evdi_add_device() fails, and
# the failure surfaces to callers as a confusing "connector never appeared".
install -D -m 0644 /dev/stdin %{buildroot}%{_modulesloaddir}/evdi.conf <<'EOF'
# Load the EVDI virtual-display module at boot.
evdi
EOF
%endif

# Generates the SRPM into /usr/src/akmods/ for akmod-evdi to ship.
# Defined by kmodtool only in the --akmod pass, hence the '?'.
%{?akmod_install}

%changelog
* Sun Jul 12 2026 Zenith <zenith@localhost> - 1.15.0-1
- Initial akmod package of the EVDI kernel module (upstream v1.15.0).
